version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: kino-web
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    restart: always

  scraper:
    build: .
    container_name: kino-scraper
    volumes:
      - ./public:/app/public
      - ./kina.sqlite:/app/kina.sqlite
    env_file:
      - .env
